# Generated by Django 4.0.8 on 2022-11-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_teacher_rating_student_image_teacher_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
